server:
  port: 8656
  servlet:
    context-path: /api

rickandmorty:
  service:
    endpoints:
      character: https://rickandmortyapi.com/api/character/
      location: https://rickandmortyapi.com/api/location/